spring:
  application:
    name: spring-architecture
  jpa:
    show_sql: true
  main:
    lazy-initialization: false

app:
  config:
    var: value_from_yaml
  manufacturer:
    engine-type: ASPIRATED
